import type { CarEvent, EventType } from "@/lib/types";

export const CATEGORIES: { type: EventType; label: string; img: number }[] = [
  { type: "show", label: "Car Shows", img: 17075732 },
  { type: "meet", label: "Meets", img: 16896020 },
  { type: "track day", label: "Track Days", img: 15155737 },
  { type: "classic", label: "Classic", img: 2272281 },
  { type: "modified", label: "Modified", img: 20406502 },
  { type: "motorsport", label: "Motorsport", img: 10373678 },
  { type: "auction", label: "Auctions", img: 34879476 },
  { type: "autojumble", label: "Autojumbles", img: 17356337 },
];

export const TYPES: EventType[] = [
  "show", "meet", "modified", "classic", "track day", "auction", "autojumble", "motorsport",
];

const SEED: CarEvent[] = [
  { id: 1, name: "Goodwood Festival of Speed", type: "motorsport", region: "South East", county: "West Sussex", town: "Chichester", venue: "Goodwood House", start: "2026-07-09", end: "2026-07-12", img: 10807493, organiser: "Goodwood", desc: "The world's greatest celebration of motorsport and car culture, from F1 cars to hypercars on the famous hillclimb.", tiers: [{ name: "Thursday", price: 39 }, { name: "Saturday", price: 69 }, { name: "Sunday", price: 79 }, { name: "4-Day Weekend", price: 215 }] },
  { id: 2, name: "Goodwood Revival", type: "motorsport", region: "South East", county: "West Sussex", town: "Chichester", venue: "Goodwood Motor Circuit", start: "2026-09-11", end: "2026-09-13", img: 10373678, organiser: "Goodwood", desc: "A glorious step back in time — historic racing and period dress celebrating motorsport's golden age.", tiers: [{ name: "Friday", price: 47 }, { name: "Saturday", price: 82 }, { name: "Sunday", price: 82 }, { name: "Weekend", price: 205 }] },
  { id: 3, name: "The British Motor Show", type: "show", region: "South East", county: "Hampshire", town: "Farnborough", venue: "Farnborough International", start: "2026-08-21", end: "2026-08-23", img: 29831803, organiser: "British Motor Show Ltd", desc: "A consumer motor show for everyone — live stunt arena, supercar paddock and EV test drives.", tiers: [{ name: "Adult Day", price: 22.5 }, { name: "Family (2+2)", price: 65 }, { name: "Weekend", price: 40 }] },
  { id: 4, name: "Silverstone Festival", type: "classic", region: "East Midlands", county: "Northamptonshire", town: "Towcester", venue: "Silverstone Circuit", start: "2026-08-22", end: "2026-08-24", img: 17075732, organiser: "Silverstone", desc: "The world's biggest classic motor racing festival — historic racing, club displays and live music.", tiers: [{ name: "Friday", price: 45 }, { name: "Saturday", price: 69 }, { name: "3-Day Festival", price: 159 }] },
  { id: 5, name: "Lancaster Insurance Classic Motor Show", type: "show", region: "West Midlands", county: "West Midlands", town: "Birmingham", venue: "NEC Birmingham", start: "2026-11-13", end: "2026-11-15", img: 17075732, organiser: "NEC Group", desc: "The UK's biggest indoor classic car show — 2,500+ classics and 300 car and bike clubs under one roof.", tiers: [{ name: "Adult Day", price: 28 }, { name: "Senior", price: 26 }, { name: "Weekend", price: 48 }] },
  { id: 6, name: "TRAX Silverstone", type: "modified", region: "East Midlands", county: "Northamptonshire", town: "Towcester", venue: "Silverstone Circuit", start: "2026-08-16", end: "2026-08-16", img: 20406502, organiser: "Fast Car", desc: "The UK's ultimate modified car show — show 'n' shine, track action and a huge trade village.", tiers: [{ name: "Advance Adult", price: 26 }, { name: "Show Car Entry", price: 40 }] },
  { id: 7, name: "Japfest Goodwood", type: "modified", region: "South East", county: "West Sussex", town: "Chichester", venue: "Goodwood Motor Circuit", start: "2026-10-03", end: "2026-10-03", img: 15155737, organiser: "Japfest", desc: "The JDM season finale — Japanese performance icons, track sessions and show 'n' shine.", tiers: [{ name: "Adult Advance", price: 24 }, { name: "Show Car Entry", price: 38 }] },
  { id: 8, name: "Beaulieu International Autojumble", type: "autojumble", region: "South East", county: "Hampshire", town: "Beaulieu", venue: "National Motor Museum", start: "2026-09-12", end: "2026-09-13", img: 17356337, organiser: "Beaulieu", desc: "Europe's largest autojumble — 2,000+ stands of parts, automobilia and project cars.", tiers: [{ name: "Adult Day", price: 20 }, { name: "Weekend", price: 34 }] },
  { id: 9, name: "Normous Newark Autojumble", type: "autojumble", region: "East Midlands", county: "Nottinghamshire", town: "Newark", venue: "Newark Showground", start: "2026-09-06", end: "2026-09-06", img: 13683840, organiser: "Newark Autojumble", desc: "One of the UK's biggest one-day autojumbles — acres of spares, tools and barn finds.", tiers: [{ name: "Adult", price: 8 }, { name: "Under 16", price: 0 }] },
  { id: 10, name: "Iconic Auctioneers — Silverstone Sale", type: "auction", region: "East Midlands", county: "Northamptonshire", town: "Towcester", venue: "The Wing, Silverstone", start: "2026-07-25", end: "2026-07-25", img: 34879476, organiser: "Iconic Auctioneers", desc: "Live classic and competition car auction at the home of British motorsport.", tiers: [{ name: "Viewing Entry", price: 12 }, { name: "Bidder Registration", price: 45 }] },
  { id: 11, name: "Iconic Auctioneers — End of Season Sale", type: "auction", region: "East Midlands", county: "Northamptonshire", town: "Towcester", venue: "The Wing, Silverstone", start: "2026-08-29", end: "2026-08-30", img: 29831803, organiser: "Iconic Auctioneers", desc: "Two days of collector cars and automobilia going under the hammer.", tiers: [{ name: "Viewing Entry", price: 12 }, { name: "Bidder Registration", price: 45 }] },
  { id: 12, name: "Iconic Auctioneers — NEC Classic Sale", type: "auction", region: "West Midlands", county: "West Midlands", town: "Birmingham", venue: "NEC Birmingham", start: "2026-11-14", end: "2026-11-14", img: 34879476, organiser: "Iconic Auctioneers", desc: "The Classic Motor Show sale — collectors' cars, motorcycles and automobilia.", tiers: [{ name: "Viewing Entry", price: 10 }, { name: "Bidder Registration", price: 45 }] },
  { id: 13, name: "Cars & Coffee London", type: "meet", region: "London", county: "Greater London", town: "London", venue: "Battersea Power Station", start: "2026-07-05", end: "2026-07-05", img: 16896020, organiser: "Cars & Coffee UK", desc: "Free monthly morning meet bringing together everything from JDM to hypercars.", tiers: [{ name: "Free Entry", price: 0 }], free: true },
  { id: 14, name: "Cars & Coffee Edinburgh", type: "meet", region: "Scotland", county: "Midlothian", town: "Edinburgh", venue: "Royal Highland Centre", start: "2026-08-02", end: "2026-08-02", img: 2272281, organiser: "Cars & Coffee Scotland", desc: "Free Sunday morning meet for the east-of-Scotland scene. All makes welcome.", tiers: [{ name: "Free Entry", price: 0 }], free: true },
  { id: 15, name: "Cars & Coffee Manchester", type: "meet", region: "North West", county: "Greater Manchester", town: "Manchester", venue: "EventCity", start: "2026-07-19", end: "2026-07-19", img: 16896020, organiser: "Cars & Coffee North", desc: "Free relaxed Sunday gathering for the North West car community.", tiers: [{ name: "Free Entry", price: 0 }], free: true },
  { id: 16, name: "Caffeine & Machine — Sunday Gather", type: "meet", region: "West Midlands", county: "Warwickshire", town: "Ettington", venue: "Caffeine & Machine", start: "2026-07-12", end: "2026-07-12", img: 2272281, organiser: "Caffeine & Machine", desc: "The famous car-culture hospitality house. Informal Sunday gathering, all welcome.", tiers: [{ name: "Free Entry", price: 0 }], free: true },
  { id: 17, name: "Bicester Sunday Scramble", type: "meet", region: "South East", county: "Oxfordshire", town: "Bicester", venue: "Bicester Heritage", start: "2026-10-04", end: "2026-10-04", img: 16896020, organiser: "Bicester Motion", desc: "Hundreds of classics gather at the historic former RAF station for a relaxed Scramble.", tiers: [{ name: "Adult Advance", price: 15 }, { name: "Under 16", price: 0 }] },
  { id: 18, name: "Brands Hatch Track Day", type: "track day", region: "South East", county: "Kent", town: "West Kingsdown", venue: "Brands Hatch", start: "2026-07-16", end: "2026-07-16", img: 15155737, organiser: "MSV Trackdays", desc: "Open-pit-lane track day on the legendary Indy circuit near London.", tiers: [{ name: "Sighting Laps", price: 25 }, { name: "Half Day", price: 129 }, { name: "Full Day", price: 199 }] },
  { id: 19, name: "Snetterton Track Day", type: "track day", region: "East of England", county: "Norfolk", town: "Norwich", venue: "Snetterton Circuit", start: "2026-07-30", end: "2026-07-30", img: 11488012, organiser: "MSV Trackdays", desc: "Fast, flowing Norfolk circuit — sessioned by experience level.", tiers: [{ name: "Passenger", price: 20 }, { name: "Half Day", price: 119 }, { name: "Full Day", price: 185 }] },
  { id: 20, name: "Oulton Park Track Day", type: "track day", region: "North West", county: "Cheshire", town: "Little Budworth", venue: "Oulton Park", start: "2026-08-13", end: "2026-08-13", img: 10807493, organiser: "MSV Trackdays", desc: "One of the UK's most scenic and challenging circuits.", tiers: [{ name: "Passenger", price: 20 }, { name: "Half Day", price: 125 }, { name: "Full Day", price: 195 }] },
  { id: 21, name: "Cadwell Park Track Day", type: "track day", region: "East Midlands", county: "Lincolnshire", town: "Louth", venue: "Cadwell Park", start: "2026-09-17", end: "2026-09-17", img: 10373678, organiser: "MSV Trackdays", desc: "The 'mini Nurburgring' — narrow, undulating and hugely rewarding.", tiers: [{ name: "Passenger", price: 20 }, { name: "Half Day", price: 115 }, { name: "Full Day", price: 179 }] },
  { id: 22, name: "Donington Park Track Day", type: "track day", region: "East Midlands", county: "Leicestershire", town: "Castle Donington", venue: "Donington Park", start: "2026-09-24", end: "2026-09-24", img: 29252120, organiser: "MSV Trackdays", desc: "Open pit lane on the historic GP circuit.", tiers: [{ name: "Passenger", price: 20 }, { name: "Half Day", price: 125 }, { name: "Full Day", price: 195 }] },
  { id: 23, name: "Castle Combe Action Day", type: "track day", region: "South West", county: "Wiltshire", town: "Chippenham", venue: "Castle Combe Circuit", start: "2026-08-27", end: "2026-08-27", img: 15155737, organiser: "Castle Combe", desc: "Open pit-lane action day on the fast Wiltshire circuit.", tiers: [{ name: "Spectator", price: 12 }, { name: "Car Driver", price: 159 }] },
  { id: 24, name: "Bedford Autodrome Track Day", type: "track day", region: "East of England", county: "Bedfordshire", town: "Bedford", venue: "Bedford Autodrome", start: "2026-10-22", end: "2026-10-22", img: 11488012, organiser: "MSV Trackdays", desc: "Wide, run-off-rich circuit — ideal for first-timers and fast laps alike.", tiers: [{ name: "Half Day", price: 129 }, { name: "Full Day", price: 199 }] },
  { id: 25, name: "Anglesey Coastal Track Day", type: "track day", region: "Wales", county: "Anglesey", town: "Ty Croes", venue: "Anglesey Circuit", start: "2026-10-10", end: "2026-10-10", img: 10807493, organiser: "TrackDays UK", desc: "Stunning coastal circuit with sea views on every lap.", tiers: [{ name: "Novice", price: 99 }, { name: "Full Day", price: 189 }] },
  { id: 26, name: "Croft Circuit Track Day", type: "track day", region: "North East", county: "North Yorkshire", town: "Darlington", venue: "Croft Circuit", start: "2026-10-15", end: "2026-10-15", img: 10373678, organiser: "BookaTrack", desc: "North East favourite — fast straights and a great mix of corners.", tiers: [{ name: "Half Day", price: 109 }, { name: "Full Day", price: 169 }] },
  { id: 27, name: "Knockhill Open Pit Lane", type: "track day", region: "Scotland", county: "Fife", town: "Dunfermline", venue: "Knockhill Racing Circuit", start: "2026-07-25", end: "2026-07-25", img: 29252120, organiser: "Knockhill", desc: "Scotland's national motorsport centre opens its pit lane for a full driver day.", tiers: [{ name: "Half Day", price: 120 }, { name: "Full Day", price: 215 }] },
  { id: 28, name: "Thruxton Track Evening", type: "track day", region: "South East", county: "Hampshire", town: "Andover", venue: "Thruxton Circuit", start: "2026-09-30", end: "2026-09-30", img: 15155737, organiser: "MSV Trackdays", desc: "The UK's fastest circuit — a high-speed evening session.", tiers: [{ name: "Half Evening", price: 99 }, { name: "Full Evening", price: 139 }] },
  { id: 29, name: "Mallory Park Track Day", type: "track day", region: "East Midlands", county: "Leicestershire", town: "Hinckley", venue: "Mallory Park", start: "2026-10-08", end: "2026-10-08", img: 11488012, organiser: "BookaTrack", desc: "Compact, friendly circuit perfect for building confidence.", tiers: [{ name: "Half Day", price: 99 }, { name: "Full Day", price: 149 }] },
  { id: 30, name: "Blyton Park Track Day", type: "track day", region: "Yorkshire", county: "Lincolnshire", town: "Gainsborough", venue: "Blyton Park", start: "2026-09-26", end: "2026-09-26", img: 10807493, organiser: "Javelin Trackdays", desc: "Versatile former airfield circuit with multiple layouts.", tiers: [{ name: "Half Day", price: 99 }, { name: "Full Day", price: 155 }] },
  { id: 31, name: "Pembrey Circuit Track Day", type: "track day", region: "Wales", county: "Carmarthenshire", town: "Llanelli", venue: "Pembrey Circuit", start: "2026-10-17", end: "2026-10-17", img: 10373678, organiser: "Javelin Trackdays", desc: "West Wales' premier circuit — technical and great value.", tiers: [{ name: "Half Day", price: 95 }, { name: "Full Day", price: 149 }] },
  { id: 32, name: "Lydden Hill Track Day", type: "track day", region: "South East", county: "Kent", town: "Dover", venue: "Lydden Hill", start: "2026-09-19", end: "2026-09-19", img: 29252120, organiser: "BookaTrack", desc: "Short, punchy Kent circuit — the home of rallycross.", tiers: [{ name: "Half Day", price: 95 }, { name: "Full Day", price: 145 }] },
  { id: 33, name: "Kirkistown Track Day", type: "track day", region: "Northern Ireland", county: "County Down", town: "Kirkistown", venue: "Kirkistown Circuit", start: "2026-08-08", end: "2026-08-08", img: 15155737, organiser: "2Fast Trackdays", desc: "Northern Ireland's fast former airfield circuit.", tiers: [{ name: "Half Day", price: 95 }, { name: "Full Day", price: 145 }] },
  { id: 34, name: "Santa Pod — Run What Ya Brung", type: "track day", region: "East Midlands", county: "Northamptonshire", town: "Wellingborough", venue: "Santa Pod Raceway", start: "2026-07-18", end: "2026-07-18", img: 11488012, organiser: "Santa Pod Raceway", desc: "Bring any road-legal car and run the famous quarter-mile drag strip.", tiers: [{ name: "Spectator", price: 15 }, { name: "RWYB Run Ticket", price: 30 }] },
  { id: 35, name: "The London Classic Car Show", type: "classic", region: "London", county: "Greater London", town: "London", venue: "Olympia London", start: "2027-02-19", end: "2027-02-21", img: 2272281, organiser: "London Classic Car Show", desc: "The capital's celebration of classic and collector cars to kick off the season.", tiers: [{ name: "Adult Day", price: 32 }, { name: "Weekend", price: 55 }] },
  { id: 36, name: "Race Retro", type: "motorsport", region: "West Midlands", county: "Warwickshire", town: "Stoneleigh", venue: "Stoneleigh Park", start: "2027-02-26", end: "2027-02-28", img: 15155737, organiser: "Race Retro", desc: "The UK's premier historic motorsport show, with live rally stages.", tiers: [{ name: "Adult Day", price: 26 }, { name: "Weekend", price: 44 }] },
  { id: 37, name: "Practical Classics Car & Restoration Show", type: "classic", region: "West Midlands", county: "West Midlands", town: "Birmingham", venue: "NEC Birmingham", start: "2027-03-19", end: "2027-03-21", img: 248687, organiser: "NEC Group", desc: "Live restoration demos, barn-find displays and thousands of spares.", tiers: [{ name: "Adult Day", price: 25 }, { name: "Senior", price: 23 }, { name: "Weekend", price: 42 }] },
  { id: 38, name: "Ultimate Dubs", type: "modified", region: "West Midlands", county: "Shropshire", town: "Telford", venue: "Telford International Centre", start: "2027-03-14", end: "2027-03-14", img: 20406502, organiser: "Ultimate Dubs", desc: "The indoor VW and stance show that opens the modified season.", tiers: [{ name: "Adult Advance", price: 22 }, { name: "Show Car", price: 38 }] },
  { id: 39, name: "Dubshed", type: "modified", region: "Northern Ireland", county: "County Antrim", town: "Lisburn", venue: "Eikon Exhibition Centre", start: "2027-03-20", end: "2027-03-21", img: 15155737, organiser: "Dubshed", desc: "Northern Ireland's biggest VAG and modified show.", tiers: [{ name: "Adult", price: 20 }, { name: "Weekend", price: 34 }] },
  { id: 40, name: "Bristol Classic Car Show", type: "classic", region: "South West", county: "Somerset", town: "Shepton Mallet", venue: "Royal Bath & West Showground", start: "2027-04-18", end: "2027-04-19", img: 13683840, organiser: "Bristol Classic", desc: "Hundreds of classics, autojumble and club stands indoors and out.", tiers: [{ name: "Adult Day", price: 14 }, { name: "Weekend", price: 24 }] },
  { id: 41, name: "Bicester Spring Scramble", type: "meet", region: "South East", county: "Oxfordshire", town: "Bicester", venue: "Bicester Heritage", start: "2027-04-25", end: "2027-04-25", img: 2272281, organiser: "Bicester Motion", desc: "The spring edition of the much-loved Sunday Scramble.", tiers: [{ name: "Adult Advance", price: 15 }, { name: "Under 16", price: 0 }] },
  { id: 42, name: "Manchester Classic & Performance Auction", type: "auction", region: "North West", county: "Greater Manchester", town: "Manchester", venue: "Manchester Central", start: "2027-04-25", end: "2027-04-25", img: 29831803, organiser: "NW Auctions", desc: "Live classic and performance car auction in the city centre.", tiers: [{ name: "Viewing Entry", price: 10 }, { name: "Bidder Registration", price: 45 }] },
  { id: 43, name: "Donington Historic Festival", type: "motorsport", region: "East Midlands", county: "Leicestershire", town: "Castle Donington", venue: "Donington Park", start: "2027-05-01", end: "2027-05-03", img: 29252120, organiser: "Donington Park", desc: "Bank Holiday historic racing with open paddocks and a huge club display.", tiers: [{ name: "Saturday", price: 25 }, { name: "Weekend", price: 40 }] },
  { id: 44, name: "Edition Show", type: "modified", region: "East Midlands", county: "Northamptonshire", town: "Sywell", venue: "Sywell Aerodrome", start: "2027-05-09", end: "2027-05-09", img: 20406502, organiser: "Edition", desc: "A curated show of the cleanest modified and stance builds in the country.", tiers: [{ name: "Spectator", price: 20 }, { name: "Show & Shine", price: 35 }] },
  { id: 45, name: "Japfest Silverstone", type: "modified", region: "East Midlands", county: "Northamptonshire", town: "Towcester", venue: "Silverstone Circuit", start: "2027-05-09", end: "2027-05-09", img: 15155737, organiser: "Japfest", desc: "Europe's biggest Japanese car festival — show 'n' shine and track action.", tiers: [{ name: "Adult Advance", price: 24 }, { name: "Show Car Entry", price: 38 }] },
  { id: 46, name: "Beaulieu Spring Autojumble", type: "autojumble", region: "South East", county: "Hampshire", town: "Beaulieu", venue: "National Motor Museum", start: "2027-05-15", end: "2027-05-16", img: 17356337, organiser: "Beaulieu", desc: "The spring autojumble — spares, automobilia and a huge classic car park.", tiers: [{ name: "Adult Day", price: 18 }, { name: "Weekend", price: 30 }] },
  { id: 47, name: "Lancashire Coast Classic & Performance Motor Show", type: "show", region: "North West", county: "Lancashire", town: "Lytham", venue: "Lytham Hall", start: "2027-05-16", end: "2027-05-16", img: 29252120, organiser: "Great British Motor Shows", desc: "Classic and performance cars in the grounds of a Georgian hall.", tiers: [{ name: "Adult Advance", price: 12 }, { name: "Family", price: 30 }] },
  { id: 48, name: "Auto Italia — Brooklands", type: "show", region: "South East", county: "Surrey", town: "Weybridge", venue: "Brooklands Museum", start: "2027-05-16", end: "2027-05-16", img: 29831803, organiser: "Auto Italia", desc: "Italian car celebration on the famous Brooklands banking.", tiers: [{ name: "Adult", price: 18 }, { name: "Family", price: 45 }] },
  { id: 49, name: "Yorkshire Classic & Performance Motor Show", type: "show", region: "Yorkshire", county: "North Yorkshire", town: "Ripley", venue: "Ripley Castle", start: "2027-05-31", end: "2027-05-31", img: 17075732, organiser: "Great British Motor Shows", desc: "Classics and modern performance cars at a stunning castle estate.", tiers: [{ name: "Adult Advance", price: 12 }, { name: "Family", price: 30 }] },
  { id: 50, name: "Players Classic", type: "modified", region: "South East", county: "West Sussex", town: "Chichester", venue: "Goodwood Motor Circuit", start: "2027-06-05", end: "2027-06-06", img: 20406502, organiser: "Players", desc: "The cult modified and stance show returns to Goodwood.", tiers: [{ name: "Spectator", price: 22 }, { name: "Show & Shine", price: 38 }] },
  { id: 51, name: "Harrogate Classic Car Spectacular", type: "classic", region: "Yorkshire", county: "North Yorkshire", town: "Harrogate", venue: "Great Yorkshire Showground", start: "2027-06-12", end: "2027-06-13", img: 29198153, organiser: "Yorkshire Classics", desc: "Classics, hot rods and Americana with arena displays and an autojumble.", tiers: [{ name: "Adult Day", price: 13 }, { name: "Weekend", price: 22 }] },
  { id: 52, name: "Longleat Motor Show Weekender", type: "show", region: "South West", county: "Wiltshire", town: "Warminster", venue: "Longleat House", start: "2027-06-26", end: "2027-06-27", img: 29252120, organiser: "Longleat", desc: "Classic displays and rally demos in the grounds of the famous safari estate.", tiers: [{ name: "Adult Day", price: 24 }, { name: "Family", price: 70 }] },
  { id: 53, name: "NE Classic & Retro Show", type: "classic", region: "North East", county: "Tyne and Wear", town: "Newcastle", venue: "Newcastle Racecourse", start: "2027-06-27", end: "2027-06-27", img: 17075732, organiser: "North East Classics", desc: "Classics, retros and modern classics gather on the racecourse infield.", tiers: [{ name: "Adult", price: 11 }, { name: "Family", price: 28 }] },
  { id: 54, name: "Anglesey Spring Track Day", type: "track day", region: "Wales", county: "Anglesey", town: "Ty Croes", venue: "Anglesey Circuit", start: "2027-04-17", end: "2027-04-17", img: 10807493, organiser: "TrackDays UK", desc: "Open the season on Britain's most scenic coastal circuit.", tiers: [{ name: "Novice", price: 99 }, { name: "Full Day", price: 189 }] },
  { id: 55, name: "Brands Hatch GP Track Day", type: "track day", region: "South East", county: "Kent", town: "West Kingsdown", venue: "Brands Hatch", start: "2027-05-21", end: "2027-05-21", img: 10373678, organiser: "MSV Trackdays", desc: "A rare chance to drive the full Brands Hatch Grand Prix loop.", tiers: [{ name: "Half Day", price: 149 }, { name: "Full Day", price: 235 }] },
  { id: 56, name: "Goodwood Breakfast Club", type: "meet", region: "South East", county: "West Sussex", town: "Chichester", venue: "Goodwood Motor Circuit", start: "2026-08-02", end: "2026-08-02", img: 16896020, organiser: "Goodwood", desc: "The legendary themed Sunday breakfast meet — arrive early, park up and soak in the atmosphere.", tiers: [{ name: "Free Entry", price: 0 }], free: true },
  { id: 57, name: "Ace Cafe London Classic Night", type: "meet", region: "London", county: "Greater London", town: "London", venue: "Ace Cafe London", start: "2026-07-11", end: "2026-07-11", img: 2272281, organiser: "Ace Cafe", desc: "The world-famous motoring cafe hosts its regular classic car and bike meet.", tiers: [{ name: "Free Entry", price: 0 }], free: true },
  { id: 58, name: "Classics on the Common", type: "meet", region: "East of England", county: "Hertfordshire", town: "Harpenden", venue: "Harpenden Common", start: "2026-07-08", end: "2026-07-08", img: 16896020, organiser: "Harpenden Lions", desc: "One of the UK's biggest free evening classic car gatherings, on the Common.", tiers: [{ name: "Free Entry", price: 0 }], free: true },
  { id: 59, name: "Cars & Coffee Birmingham", type: "meet", region: "West Midlands", county: "West Midlands", town: "Birmingham", venue: "Resorts World", start: "2026-07-26", end: "2026-07-26", img: 2272281, organiser: "Cars & Coffee Midlands", desc: "Free Sunday morning meet for the Midlands car community.", tiers: [{ name: "Free Entry", price: 0 }], free: true },
  { id: 60, name: "Cars & Coffee Bristol", type: "meet", region: "South West", county: "Bristol", town: "Bristol", venue: "Aztec West", start: "2026-08-09", end: "2026-08-09", img: 16896020, organiser: "Cars & Coffee South West", desc: "Relaxed free morning gathering — all makes and models welcome.", tiers: [{ name: "Free Entry", price: 0 }], free: true },
  { id: 61, name: "Cars & Coffee Leeds", type: "meet", region: "Yorkshire", county: "West Yorkshire", town: "Leeds", venue: "Elland Road", start: "2026-08-16", end: "2026-08-16", img: 2272281, organiser: "Cars & Coffee Yorkshire", desc: "Free Sunday meet bringing out the best of the Yorkshire scene.", tiers: [{ name: "Free Entry", price: 0 }], free: true },
  { id: 62, name: "Cars & Coffee Cardiff", type: "meet", region: "Wales", county: "Cardiff", town: "Cardiff", venue: "Cardiff Bay", start: "2026-08-23", end: "2026-08-23", img: 16896020, organiser: "Cars & Coffee Cymru", desc: "Free waterfront morning meet for the South Wales community.", tiers: [{ name: "Free Entry", price: 0 }], free: true },
  { id: 63, name: "Cars & Coffee Belfast", type: "meet", region: "Northern Ireland", county: "County Antrim", town: "Belfast", venue: "Titanic Quarter", start: "2026-08-30", end: "2026-08-30", img: 2272281, organiser: "Cars & Coffee NI", desc: "Free Sunday gathering in the heart of Belfast's Titanic Quarter.", tiers: [{ name: "Free Entry", price: 0 }], free: true },
  { id: 64, name: "Newcastle Quayside Car Meet", type: "meet", region: "North East", county: "Tyne and Wear", town: "Newcastle", venue: "Newcastle Quayside", start: "2026-08-15", end: "2026-08-15", img: 16896020, organiser: "Quayside Meets", desc: "Free evening riverside meet — modern, modified and classic.", tiers: [{ name: "Free Entry", price: 0 }], free: true },
  { id: 65, name: "Petrolheads Sunday Breakfast Meet", type: "meet", region: "South East", county: "Surrey", town: "Guildford", venue: "Newlands Corner", start: "2026-07-26", end: "2026-07-26", img: 2272281, organiser: "Petrolheads", desc: "Popular hillside breakfast meet with sweeping views across the Surrey Hills.", tiers: [{ name: "Free Entry", price: 0 }], free: true },
  { id: 66, name: "The Lygon Arms Pub Meet", type: "meet", region: "West Midlands", county: "Worcestershire", town: "Broadway", venue: "The Lygon Arms", start: "2026-08-12", end: "2026-08-12", img: 16896020, organiser: "Cotswold Car Club", desc: "Relaxed midweek evening pub meet in the heart of the Cotswolds.", tiers: [{ name: "Free Entry", price: 0 }], free: true },
  { id: 67, name: "Crystal Palace Sunday Meet", type: "meet", region: "London", county: "Greater London", town: "London", venue: "Crystal Palace Park", start: "2026-09-06", end: "2026-09-06", img: 2272281, organiser: "Palace Meets", desc: "Free South London Sunday gathering on the historic motor-racing site.", tiers: [{ name: "Free Entry", price: 0 }], free: true },
];

export function getAllEvents(): CarEvent[] {
  return SEED;
}

// Only events whose end date is today or later — past events expire automatically.
export function getUpcomingEvents(): CarEvent[] {
  const today = new Date().toISOString().slice(0, 10);
  return SEED.filter((e) => e.end >= today).sort((a, b) => a.start.localeCompare(b.start));
}

export function getEventById(id: number): CarEvent | undefined {
  return SEED.find((e) => e.id === id);
}

export const REGIONS: string[] = Array.from(new Set(SEED.map((e) => e.region))).sort();
