import type { CarEvent } from "@/lib/types";

// Time Attack Ltd — first directory partner (added 22 Jul 2026, organiser confirmed by email).
// Their 2026 consumer shows: modified/JDM car shows with Time Attack Championship track action.
// Images + prices sourced from each event's own official site. Ticketing handled by the venue (MSV).
export const SEED_7: CarEvent[] = [
  {
    id: 19001,
    name: "Modified Live — Snetterton",
    type: "modified",
    region: "East of England",
    county: "Norfolk",
    town: "Snetterton",
    venue: "Snetterton Circuit",
    start: "2026-08-02",
    end: "2026-08-02",
    img: 20406502,
    imgUrl: "https://snetterton.modifiedlive.co.uk/wp-content/uploads/sites/5/2025/12/TA2025-R4-SA-24-scaled.jpg",
    organiser: "Time Attack Ltd",
    desc: "The modified-car show lands at Snetterton for a new summer date — huge club and individual car displays, the Obsession Car Show, drifting demos and the Time Attack Championship on track, plus a full food and trade village. 10,000+ enthusiasts. Under-13s free, teens (13–15) £15 advance.",
    tiers: [{ name: "Adult (advance)", price: 24 }],
    free: false,
    bookingUrl: "https://snetterton.modifiedlive.co.uk/tickets/",
  },
  {
    id: 19002,
    name: "Go Japan! — Brands Hatch",
    type: "modified",
    region: "South East",
    county: "Kent",
    town: "Longfield",
    venue: "Brands Hatch Circuit",
    start: "2026-08-31",
    end: "2026-08-31",
    img: 20406502,
    imgUrl: "https://www.gojapan.co.uk/wp-content/uploads/sites/6/2025/12/TAO2025-Go-Japan-217-scaled.jpg",
    organiser: "Time Attack Ltd",
    desc: "A celebration of Japanese car culture at the home of Time Attack — iconic JDM machines, the Obsession Car Show, drifting, cosplay and the Time Attack Championship on track. Bank Holiday Monday. Under-13s free, teens (13–15) £18 advance.",
    tiers: [{ name: "Adult (advance)", price: 26 }],
    free: false,
    bookingUrl: "https://www.gojapan.co.uk/ticket-info/",
  },
  {
    id: 19003,
    name: "Modified Live Finale — Cadwell Park",
    type: "modified",
    region: "East Midlands",
    county: "Lincolnshire",
    town: "Louth",
    venue: "Cadwell Park",
    start: "2026-09-20",
    end: "2026-09-20",
    img: 20406502,
    imgUrl: "https://snetterton.modifiedlive.co.uk/wp-content/uploads/sites/5/2025/12/TA2025-R4-SA-24-scaled.jpg",
    organiser: "Time Attack Ltd",
    desc: "The 2026 season finale — Modified Live returns to the spectacular Cadwell Park for a huge send-off of car displays, the Obsession Car Show, drifting and the final round of the Time Attack Championship. Under-13s free, teens (13–15) £15 advance.",
    tiers: [{ name: "Adult (advance)", price: 24 }],
    free: false,
    bookingUrl: "https://finale.modifiedlive.co.uk/",
  },
];
