import type { CarEvent } from "@/lib/types";

// Major UK shows sourced from each organiser's own site (Ford Fair, Concours of Elegance, RAC London to Brighton, Beaulieu).
export const SEED_6: CarEvent[] = [
  { id: 1401, name: "Ford Fair", type: "modified", region: "East Midlands", county: "Northamptonshire", town: "Towcester", venue: "Silverstone Circuit", start: "2026-08-23", end: "2026-08-23", img: 20406502, organiser: "Ford Fair / Kelsey Media", desc: "Europe's biggest fast-Ford show returns to Silverstone for its 40th year — 3,500+ cars, club displays, track time, drifting and the Fastest Fords line-up.", tiers: [{ name: "Club", price: 28 }, { name: "Public", price: 30 }], free: false, bookingUrl: "https://kelsey.eventsair.com/ford-fair-2026/tickets" },
  { id: 1402, name: "Concours of Elegance", type: "classic", region: "South East", county: "Surrey", town: "East Molesey", venue: "Hampton Court Palace", start: "2026-09-04", end: "2026-09-06", img: 2272281, organiser: "Thorough Events", desc: "Sixty of the rarest cars in the world gathered in the gardens of Hampton Court Palace — the UK's premier concours, with club displays and luxury exhibitors.", tiers: [{ name: "Afternoon (Sat/Sun)", price: 51 }, { name: "Adult Day", price: 71.4 }, { name: "VIP Preview (Fri)", price: 112.2 }], free: false, bookingUrl: "https://concoursofelegance.co.uk/tickets/" },
  { id: 1403, name: "RM Sotheby's London to Brighton Veteran Car Run", type: "classic", region: "London", county: "Greater London", town: "London", venue: "Hyde Park (start)", start: "2026-11-01", end: "2026-11-01", img: 2272281, organiser: "Royal Automobile Club", desc: "The world's longest-running motoring event — hundreds of pre-1905 veteran cars set off from Hyde Park at dawn for the 60-mile run to Brighton. Free to spectate along the route.", tiers: [{ name: "Spectator", price: 0 }], free: true, bookingUrl: "https://www.veterancarrun.com/spectators" },
  { id: 1404, name: "Swedish Takeover at Beaulieu", type: "show", region: "South East", county: "Hampshire", town: "Beaulieu", venue: "National Motor Museum, Beaulieu", start: "2026-07-04", end: "2026-07-04", img: 17075732, organiser: "Beaulieu", desc: "Volvo and Saab enthusiasts take over Beaulieu for a celebration of Swedish motoring, included with museum admission.", tiers: [{ name: "Adult (advance)", price: 24.8 }], free: false, bookingUrl: "https://www.beaulieu.co.uk/events/swedish-takeover/" },
  { id: 1405, name: "Simply Land Rover", type: "show", region: "South East", county: "Hampshire", town: "Beaulieu", venue: "National Motor Museum, Beaulieu", start: "2026-07-05", end: "2026-07-05", img: 17075732, organiser: "Beaulieu", desc: "A superb day out for Land Rover owners and enthusiasts, with a rally field of every era of the off-road icon.", tiers: [{ name: "Adult (advance)", price: 24.8 }], free: false, bookingUrl: "https://www.beaulieu.co.uk/events/simply-land-rover/" },
  { id: 1406, name: "Simply Audi", type: "show", region: "South East", county: "Hampshire", town: "Beaulieu", venue: "National Motor Museum, Beaulieu", start: "2026-07-18", end: "2026-07-18", img: 17075732, organiser: "Beaulieu", desc: "An impressive display for the German marque — quattros, RS and everything in between, on the Beaulieu rally field.", tiers: [{ name: "Adult (advance)", price: 24.8 }], free: false, bookingUrl: "https://www.beaulieu.co.uk/events/simply-audi/" },
  { id: 1407, name: "Simply Japanese", type: "show", region: "South East", county: "Hampshire", town: "Beaulieu", venue: "National Motor Museum, Beaulieu", start: "2026-07-19", end: "2026-07-19", img: 17075732, organiser: "Beaulieu", desc: "A great day out for all Japanese car owners and enthusiasts, from JDM legends to modern performance heroes.", tiers: [{ name: "Adult (advance)", price: 24.8 }], free: false, bookingUrl: "https://www.beaulieu.co.uk/events/simply-japanese/" },
  { id: 1408, name: "Beaulieu Supercar Weekend", type: "show", region: "South East", county: "Hampshire", town: "Beaulieu", venue: "National Motor Museum, Beaulieu", start: "2026-08-01", end: "2026-08-02", img: 17075732, organiser: "Beaulieu", desc: "A two-day celebration of all things supercar at Beaulieu — hypercars, exotics and the cars of your dreams.", tiers: [{ name: "Adult (advance)", price: 24.8 }], free: false, bookingUrl: "https://www.beaulieu.co.uk/events/beaulieu-supercar-weekend/" },
  { id: 1409, name: "Simply Mercedes", type: "show", region: "South East", county: "Hampshire", town: "Beaulieu", venue: "National Motor Museum, Beaulieu", start: "2026-08-09", end: "2026-08-09", img: 17075732, organiser: "Beaulieu", desc: "A superb day out for Mercedes-Benz owners and enthusiasts on the Beaulieu rally field.", tiers: [{ name: "Adult (advance)", price: 24.8 }], free: false, bookingUrl: "https://www.beaulieu.co.uk/events/simply-mercedes/" },
  { id: 1410, name: "Simply Jaguar", type: "show", region: "South East", county: "Hampshire", town: "Beaulieu", venue: "National Motor Museum, Beaulieu", start: "2026-08-16", end: "2026-08-16", img: 17075732, organiser: "Beaulieu", desc: "An impressive display open to all classic and modern Jaguars, from XK to F-Type.", tiers: [{ name: "Adult (advance)", price: 24.8 }], free: false, bookingUrl: "https://www.beaulieu.co.uk/events/simply-jaguar/" },
  { id: 1411, name: "Simply Aston Martin", type: "show", region: "South East", county: "Hampshire", town: "Beaulieu", venue: "National Motor Museum, Beaulieu", start: "2026-08-23", end: "2026-08-23", img: 17075732, organiser: "Beaulieu", desc: "A fantastic day out for Aston Martin owners and enthusiasts at the home of the National Motor Museum.", tiers: [{ name: "Adult (advance)", price: 24.8 }], free: false, bookingUrl: "https://www.beaulieu.co.uk/events/simply-aston-martin-3/" },
  { id: 1412, name: "The Beaulieu Oak Run", type: "classic", region: "South East", county: "Hampshire", town: "Beaulieu", venue: "National Motor Museum, Beaulieu", start: "2026-09-06", end: "2026-09-06", img: 2272281, organiser: "Beaulieu", desc: "Pre-1905 veteran vehicles take a route through the New Forest and gather at Beaulieu for this charming run.", tiers: [{ name: "Adult (advance)", price: 28.35 }], free: false, bookingUrl: "https://www.beaulieu.co.uk/events/the-beaulieu-oak-run/" },
  { id: 1413, name: "Simply BMW", type: "show", region: "South East", county: "Hampshire", town: "Beaulieu", venue: "National Motor Museum, Beaulieu", start: "2026-09-20", end: "2026-09-20", img: 17075732, organiser: "Beaulieu", desc: "A fantastic day out for BMW owners and enthusiasts, from classic 02s to modern M cars.", tiers: [{ name: "Adult (advance)", price: 28.35 }], free: false, bookingUrl: "https://www.beaulieu.co.uk/events/simply-bmw/" },
  { id: 1414, name: "VauxALL South", type: "show", region: "South East", county: "Hampshire", town: "Beaulieu", venue: "National Motor Museum, Beaulieu", start: "2026-09-26", end: "2026-09-26", img: 17075732, organiser: "Beaulieu", desc: "All Vauxhall, Opel and Bedford owners are invited to this end-of-season celebration on the Beaulieu rally field.", tiers: [{ name: "Adult (advance)", price: 28.35 }], free: false, bookingUrl: "https://www.beaulieu.co.uk/events/vauxall_south/" },
  { id: 1415, name: "Simply Italian", type: "show", region: "South East", county: "Hampshire", town: "Beaulieu", venue: "National Motor Museum, Beaulieu", start: "2026-09-27", end: "2026-09-27", img: 17075732, organiser: "Beaulieu", desc: "A fantastic day out for Italian car owners and enthusiasts — Ferrari, Alfa, Fiat, Lancia and more.", tiers: [{ name: "Adult (advance)", price: 28.35 }], free: false, bookingUrl: "https://www.beaulieu.co.uk/events/simply-italian/" },
  { id: 1416, name: "Simply Smart", type: "show", region: "South East", county: "Hampshire", town: "Beaulieu", venue: "National Motor Museum, Beaulieu", start: "2026-11-08", end: "2026-11-08", img: 17075732, organiser: "Beaulieu", desc: "A fabulous day out for Smart car owners and enthusiasts to close out the Beaulieu Simply season.", tiers: [{ name: "Adult (advance)", price: 28.35 }], free: false, bookingUrl: "https://www.beaulieu.co.uk/events/simply-smart/" },
];
